### ISSUE TITLE
recv failed: Resource unavailable when selecting app

### ISSUE THREAD

**Issue by bensh** [dmayer/idb#108]
idb 2.10.3
ruby 2.1.8
iOS 10.0.2

Connects fine via usb, click on select an app which lists them fine, select the app and it crashes.

```
#<Plist4r::Plist:0x007fa0061efea8>
/Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/app_details_group_box.rb:69:in `app_changed': undefined method `sub' for nil:NilClass (NoMethodError)
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/app_tab_widget.rb:48:in `app_changed'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/main_tab_widget.rb:163:in `app_changed'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/idb.rb:122:in `block in init_ui'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/global_app_details_group_box.rb:61:in `qt_metacall'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/global_app_details_group_box.rb:61:in `app_changed'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/global_app_details_group_box.rb:61:in `block (2 levels) in initialize'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/app_list_dialog.rb:24:in `qt_metacall'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/app_list_dialog.rb:24:in `method_missing'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/app_list_dialog.rb:24:in `block in initialize'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:917:in `qt_metacall'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:917:in `method_missing'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:917:in `exec'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/gui/global_app_details_group_box.rb:63:in `block in initialize'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `exec'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/lib/idb.rb:278:in `run'
	from /Users/ben/.rvm/gems/ruby-2.1.8/gems/idb-2.10.3/bin/idb:4:in `<top (required)>'
	from /Users/ben/.rvm/gems/ruby-2.1.8/bin/idb:23:in `load'
	from /Users/ben/.rvm/gems/ruby-2.1.8/bin/idb:23:in `<main>'
	from /Users/ben/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ben/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `<main>'
recv failed: Resource temporarily unavailable
```

**Comment by eaneatfruit** [comment]
I have experienced the same issue. Unable to get past this point.
