### ISSUE TITLE
IDB crashes once an application is selected

### ISSUE THREAD

**Issue by prithiviraj** [dmayer/idb#109]
IDB closes once an application is selected.
1. "Select App..." displays the current application
2. IDB closes after the application is selected. Below is the stack trace info received.

 3: from /usr/local/lib/ruby/gems/2.5.0/gems/idb-2.10.3/lib/idb.rb:122:in `block in init_ui'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/idb-2.10.3/lib/gui/main_tab_widget.rb:163:in `app_changed'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/idb-2.10.3/lib/gui/app_tab_widget.rb:48:in `app_changed'
/usr/local/lib/ruby/gems/2.5.0/gems/idb-2.10.3/lib/gui/app_details_group_box.rb:69:in `app_changed': undefined method `sub' for nil:NilClass (NoMethodError)
recv failed: Resource temporarily unavailable

**Comment by andreykostakov** [comment]
Same here. 
Faced with problem on iPhone 5c 10.3.3 and iPhone 6s 10.3.3

**Comment by adaghma** [comment]
Same issue iPad 4 10.3.3

**Comment by mechanico** [comment]
see #105
