### ISSUE TITLE
IDB Crashing IOS 11.2.6 When selecting the app

### ISSUE THREAD

**Issue by f5ocietyh4x0rz** [dmayer/idb#112]
IDB is crashing on me when I am selecting the application to work with. Here are the log details - 
raceback (most recent call last):
	37: from /usr/local/bin/idb:23:in `<main>'
	36: from /usr/local/bin/idb:23:in `load'
	35: from /var/lib/gems/2.5.0/gems/idb-2.10.3/bin/idb:4:in `<top (required)>'
	34: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/idb.rb:278:in `run'
	33: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `exec'
	32: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `method_missing'
	31: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	30: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:2470:in `invoke'
	29: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/global_app_details_group_box.rb:63:in `block in initialize'
	28: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:917:in `exec'
	27: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:917:in `method_missing'
	26: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:917:in `qt_metacall'
	25: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:2470:in `invoke'
	24: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/app_list_dialog.rb:24:in `block in initialize'
	23: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/app_list_dialog.rb:24:in `method_missing'
	22: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/app_list_dialog.rb:24:in `qt_metacall'
	21: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:2470:in `invoke'
	20: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/global_app_details_group_box.rb:61:in `block (2 levels) in initialize'
	19: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/global_app_details_group_box.rb:61:in `app_changed'
	18: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/global_app_details_group_box.rb:61:in `qt_metacall'
	17: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:2470:in `invoke'
	16: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/idb.rb:122:in `block in init_ui'
	15: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/main_tab_widget.rb:159:in `app_changed'
	14: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/main_tab_widget.rb:95:in `enableLocalStorage'
	13: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/local_storage_tab_widget.rb:25:in `setup'
	12: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/plist_file_widget.rb:52:in `setup'
	11: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/gui/default_protection_class_group_widget.rb:23:in `update'
	10: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/lib/app.rb:300:in `entitlements'
	 9: from /var/lib/gems/2.5.0/gems/idb-2.10.3/lib/lib/ios10_application_state_db_wrapper.rb:28:in `entitlements_by_binary'
	 8: from /var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r.rb:20:in `new'
	 7: from /var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r.rb:20:in `new'
	 6: from /var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r/plist.rb:53:in `initialize'
	 5: from /var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r/plist.rb:277:in `parse_opts'
	 4: from /var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r/plist.rb:277:in `each'
	 3: from /var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r/plist.rb:280:in `block in parse_opts'
	 2: from /var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r/plist.rb:80:in `from_string'
	 1: from /var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r/plist_cache.rb:22:in `from_string'
/var/lib/gems/2.5.0/gems/plist4r-1.2.2/lib/plist4r/backend.rb:146:in `call': Failure(s) while executing method :from_string on plist #<Plist4r::Plist:0x0000560d108ffb10>. (RuntimeError)
root@fsociety:~#

**Comment by nikhilgeo** [comment]
I'm also hit with the same issue on iOS 11.2.6
