### ISSUE TITLE
No longer working on OSX

### ISSUE THREAD

**Issue by n0x00** [dmayer/idb#62]
I've tried to install this with all required dependencies on OSX 

Is there a Virtual Machine anywhere ?

ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

Darwin null.home 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

my osx failings come by way of  something in the following output 
`` /Users/null/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:70:in `initialize': Connection refused - connect(2) for "localhost" port 51809 (Errno::ECONNREFUSED)
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:70:in `open'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:70:in `block in initialize'
	from /Users/null/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
	from /Users/null/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:67:in `initialize'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh.rb:207:in `new'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.2/lib/net/ssh.rb:207:in `start'
	from /Users/null/sec/idb/lib/lib/ssh_port_forwarder.rb:17:in `initialize'
	from /Users/null/sec/idb/lib/lib/../helper/ssh_port_forwarder.rb:36:in `new'
	from /Users/null/sec/idb/lib/lib/../helper/ssh_port_forwarder.rb:36:in `run'
	from /Users/null/sec/idb/lib/lib/../helper/ssh_port_forwarder.rb:63:in `<module:Idb>'
	from /Users/null/sec/idb/lib/lib/../helper/ssh_port_forwarder.rb:7:in `<main>'
waiting for connection
[INFO] 2015-08-26 12:54:39 :: idb ::  Checking if aptget is installed..``

OR 

``2015-08-26 12:54:41.340 ruby[25618:3520555] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
``

OR

`` INFO] 2015-08-26 12:55:14 :: idb ::  Parsing plist file..
[ERROR] 2015-08-26 12:55:14 :: idb ::  Info.plist not found.
[ERROR] 2015-08-26 12:55:14 :: idb ::  Info.plist not found.
[ERROR] 2015-08-26 12:55:14 :: idb ::  Error getting plist file .
[DEBUG] 2015-08-26 12:55:14 :: idb ::  Exception Details: undefined method `sub' for nil:NilClass.
[DEBUG] 2015-08-26 12:55:14 :: idb ::  Backtrace: /Users/null/sec/idb/lib/lib/app.rb:255:in `cache_file'
/Users/null/sec/idb/lib/lib/app.rb:271:in `parse_info_plist'
/Users/null/sec/idb/lib/lib/app.rb:17:in `initialize'
/Users/null/sec/idb/lib/gui/app_list_dialog.rb:76:in `new'
/Users/null/sec/idb/lib/gui/app_list_dialog.rb:76:in `block in refresh_app_list'
/Users/null/sec/idb/lib/gui/app_list_dialog.rb:75:in `each'
/Users/null/sec/idb/lib/gui/app_list_dialog.rb:75:in `refresh_app_list'
/Users/null/sec/idb/lib/gui/app_list_dialog.rb:33:in `initialize'
/Users/null/sec/idb/lib/gui/global_app_details_group_box.rb:43:in `new'
/Users/null/sec/idb/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
/Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:2454:in `call'
/Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:2454:in `invoke'
/Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in `qt_metacall'
/Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in `method_missing'
/Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in `exec'
/Users/null/sec/idb/lib/idb.rb:285:in `run'
/Users/null/sec/idb/bin/idb:4:in `<top (required)>'
/Users/null/.rvm/gems/ruby-2.1.5/bin/idb:23:in `load'
/Users/null/.rvm/gems/ruby-2.1.5/bin/idb:23:in `<main>'
/Users/null/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/null/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'.
/Users/null/sec/idb/lib/lib/app.rb:24:in `initialize': undefined method `bundle_identifier' for nil:NilClass (NoMethodError)
	from /Users/null/sec/idb/lib/gui/app_list_dialog.rb:76:in `new'
	from /Users/null/sec/idb/lib/gui/app_list_dialog.rb:76:in `block in refresh_app_list'
	from /Users/null/sec/idb/lib/gui/app_list_dialog.rb:75:in `each'
	from /Users/null/sec/idb/lib/gui/app_list_dialog.rb:75:in `refresh_app_list'
	from /Users/null/sec/idb/lib/gui/app_list_dialog.rb:33:in `initialize'
	from /Users/null/sec/idb/lib/gui/global_app_details_group_box.rb:43:in `new'
	from /Users/null/sec/idb/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:2454:in `call'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:2454:in `invoke'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /Users/null/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in `exec'
	from /Users/null/sec/idb/lib/idb.rb:285:in `run'
	from /Users/null/sec/idb/bin/idb:4:in `<top (required)>'
	from /Users/null/.rvm/gems/ruby-2.1.5/bin/idb:23:in `load'
	from /Users/null/.rvm/gems/ruby-2.1.5/bin/idb:23:in `<main>'
	from /Users/null/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/null/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
recv failed: Resource temporarily unavailable
 ``

**Comment by dmayer** [comment]
Hi,

we should try to work on one of the error message, they all have very different reasons. The first one seems to be a problem with even connecting to the device via SSH. Can you check if you have `iproxy` on the command line?

The second one is not an error, its just something Qt sometimes spits out without any impact on the app.

The third one seems to be a different problem. Is it possibe that you don't have any apps installed on the device? It seems idb can't find the Info.plist file for one of your apps. Would be good if we could narrow down why that is the case and I can fix it, so that it doesn't crash.

**Comment by ejohn20** [comment]
I also recently ran into this problem on OSX. Background, it was working fine for quite a while. I used the tool in mid-July on the phone that has not been modified in months. Worked just fine.

Fired it up again early August, and it crashes when trying to open the iGoat.app file. After selecting the app and pressing the button to analyze it, this stack trace appears:

[INFO] 2016-09-08 15:29:37 :: idb ::  Info.plist found at /private/var/mobile/Containers/Bundle/Application/FE1B6DD3-5583-4D8E-8903-4AB4680F17D6/iGoat.app/Info.plist
[INFO] 2016-09-08 15:29:37 :: idb ::  Parsing plist file..
[INFO] 2016-09-08 15:29:41 :: idb ::  Icon found at /private/var/mobile/Containers/Bundle/Application/FE1B6DD3-5583-4D8E-8903-4AB4680F17D6/iGoat.app/Icon@2x.png
/Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/default_protection_class_group_widget.rb:25:in `update': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/plist_file_widget.rb:52:in `setup'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/local_storage_tab_widget.rb:25:in `setup'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/main_tab_widget.rb:111:in `enableLocalStorage'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/main_tab_widget.rb:178:in `app_changed'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/idb.rb:129:in `block in init_ui'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/global_app_details_group_box.rb:61:in `qt_metacall'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/global_app_details_group_box.rb:61:in `app_changed'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/global_app_details_group_box.rb:61:in `block (2 levels) in initialize'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:26:in `qt_metacall'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:26:in `method_missing'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:26:in `block in initialize'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:917:in `qt_metacall'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:917:in `method_missing'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:917:in `exec'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/gui/global_app_details_group_box.rb:63:in `block in initialize'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `exec'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/lib/idb.rb:285:in `run'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/gems/idb-2.8.5/bin/idb:4:in `<top (required)>'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/bin/idb:23:in `load'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/bin/idb:23:in `<main>'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/EJ/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
recv failed: Resource temporarily unavailable

**Comment by learntofly83** [comment]
Im not a software developer, intact this is my first time playing with ruby....

Somehow I've managed to get idb from GitHub running on Sierra.... I made a few mistakes along the way, however Ive exported my history file and tried to reconstruct the steps that got this working...

I may have some of this wrong but its a starter for 10 (ignore the three digit numbers at the start of each line)


===

  288  brew prune
  289  xcode-select --install
  308  command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
  309  \curl -L https://get.rvm.io | bash -s stable
  310  rvm get stable --autolibs=enable
  312  rvm install ruby-2.3.3
  313  gem update --system
  475  brew update && brew upgrade
  476  brew uninstall qt
  477  brew remove qt
  478  brew tap cartr/qt4
  479  brew tap-pin cartr/qt4
  480  brew install qt
  481  brew linkapps qt
  482  brew install cmake usbmuxd libimobiledevice
  484  rvm gemset list
  485  rvm gemset use global
  486  rvm get stable --auto-dotfiles
  487  gem outdated
  488  gem update
  490  gem install bundler
  491  gem install nokogirl
  492  rvm use ruby-2.3.3@rails5.0.0.1 --create --enable-shared --with-gcc=clang
  494  gem install rails
  495  gem install qtbindings
  497  brew install ldid dpkg
  420  git clone https://github.com/dmayer/idb
  421  cd idb
  427  bundle update
  428  bundle install
  429  bundle exec idb

===


Please by all means if someone can reproduce the exact steps, feel free to alter

LTF

**Comment by dmayer** [comment]
Hey @ejohn20 , sorry for the lack of responsiveness. I know this is a really old bug but I am catching up on old issues. If you happen to still use idb, is this still an issue? If so, I will look into it :)
