### ISSUE TITLE
QT4 EOL

### ISSUE THREAD

**Issue by Wingless-Archangel** [dmayer/idb#79]
currently, I couldn't install qt with your documentation anymore. From the research around the internet, I found that QT4 is EOL. Any plans to move on to QT5?

Please find the error below.

```
$ brew install qt
qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

**Comment by smhome** [comment]
Hi, 

this helped me: https://github.com/Homebrew/homebrew-core/issues/6232

The installation worked fine. Unfortunately, after starting idb and trying to open the Settings idb crashes with following output:

```
QLayout: Cannot add null widget to QGridLayout/
/Users/user/idb/lib/lib/settings.rb:56:in `rescue in method_missing': undefined method `sqlite_editor' for #<Idb::Settings:0x007fba766e2458> (NoMethodError)
	from /Users/user/idb/lib/lib/settings.rb:53:in `method_missing'
	from /Users/user/idb/lib/gui/settings_tab_widget.rb:125:in `setup_external_apps'
	from /Users/user/idb/lib/gui/settings_tab_widget.rb:15:in `initialize'
	from /Users/user/idb/lib/gui/settings_dialog.rb:14:in `new'
	from /Users/user/idb/lib/gui/settings_dialog.rb:14:in `initialize'
	from /Users/user/idb/lib/idb.rb:150:in `new'
	from /Users/user/idb/lib/idb.rb:150:in `block in menu'
	from /Users/user/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/user/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/user/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /Users/user/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /Users/user/.rvm/gems/ruby-2.1.8/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `exec'
	from /Users/user/idb/lib/idb.rb:278:in `run'
	from /Users/user/idb/bin/idb:4:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.1.8/bin/idb:23:in `load'
	from /Users/user/.rvm/gems/ruby-2.1.8/bin/idb:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `<main>'
```
Any help on this?

**Comment by smhome** [comment]
Ok, i found a workaround.

I manually edited the settings.yml file which is located under .idb in the home user's directory, making it look like:

```
ssh_host: <enter ip address of iOS device here>
ssh_port: 22
ssh_username: root
ssh_password: <enter root password here>
manual_ssh_port: '2222'
idb_utility_port: '4711'
device_connection_mode: ssh
remote_forwards: []
local_forwards: []
sqlite_editor:
```

Now I'm also able to enter the preferences!

**Comment by moloch--** [comment]
To fix:

```
brew tap cartr/qt4
brew tap-pin cartr/qt4
brew install cartr/qt4/qt@4
```

**Comment by dmayer** [comment]
Finally looked deeper into this. Unfortunately there are no Qt5 bindings for ruby available. So we are stuck using Qt4. I will update documentation to add the additional steps posted by @moloch-- . thanks a lot for those!

**Comment by Wingless-Archangel** [comment]
from [stackoverflow](https://stackoverflow.com/questions/23002361/does-qtruby-work-with-qt-5`) we could use Ruby-QML.

**Comment by Wingless-Archangel** [comment]
For more information, @dmayer, I just found this project in github, https://github.com/kitech/ruby-jit-qt, A Qt5 binding for Ruby language. Using clang/llvm JIT engine.
