### ISSUE TITLE
idb crash on clicking analyze package (for PIE, stack protection)

### ISSUE THREAD

**Issue by whitehatpanda** [dmayer/idb#80]
I get idb crash when trying to analyze application (PIE...). I'm using your release 2.8.5, because of I can't run > idb on 2.9.0 (lastest).

Here my error log:
2016-11-03 14:43:45.476 ruby[34026:3412284] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
[INFO] 2016-11-03 14:43:48 :: idb ::  Locating application binary...
/Users/whitehatpanda/Downloads/idb-2.8.5/lib/lib/otool_wrapper.rb:72:in `parse_header': undefined method `split' for nil:NilClass (NoMethodError)
	from /Users/whitehatpanda/Downloads/idb-2.8.5/lib/lib/otool_wrapper.rb:23:in `initialize'
	from /Users/whitehatpanda/Downloads/idb-2.8.5/lib/lib/app_binary.rb:8:in `new'
	from /Users/whitehatpanda/Downloads/idb-2.8.5/lib/lib/app_binary.rb:8:in `initialize'
	from /Users/whitehatpanda/Downloads/idb-2.8.5/lib/lib/app.rb:36:in `new'
	from /Users/whitehatpanda/Downloads/idb-2.8.5/lib/lib/app.rb:36:in `analyze'
	from /Users/whitehatpanda/Downloads/idb-2.8.5/lib/gui/app_details_group_box.rb:190:in `block in initialize'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `exec'
	from /Users/whitehatpanda/Downloads/idb-2.8.5/lib/idb.rb:285:in `run'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/gems/idb-2.9.0/bin/idb:4:in `<top (required)>'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/bin/idb:23:in `load'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/bin/idb:23:in `<main>'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/whitehatpanda/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
recv failed: Resource temporarily unavailable

**Comment by dmayer** [comment]
Hi, sorry for the real late reply. Got busy at work and didn't have time to check in on these issues. Are you still using idb and are running into this issue? If so, try updating to 2.9.3. Which iOS version are you using. Also, can you share which app gave you trouble?

Thanks.
