### ISSUE TITLE
Error when connecting to device

### ISSUE THREAD

**Issue by rromanen** [dmayer/idb#92]
Hi,
I get an error when I click to connect to device, then input the root password as prompted and this is the error I get. on latest idb version as it was installed today, using iOS 8.3. 

waiting for connection
[INFO] 2017-07-27 17:08:57 :: port_forward :: Establishing SSH port forwarding...
accepted connection, fd = 4
Number of available devices == 1
Requesting connecion to device handle == 3 (serial: a881fd275cb6c7e23b17f501ed3a2ab5deb2831b), port 22
waiting for connection
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
root@localhost's password:/Users/roman/.rvm/gems/ruby-2.4.1/gems/net-ssh-4.1.0/lib/net/ssh/prompt.rb:44:in `noecho': Input/output error (Errno::EIO)
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/net-ssh-4.1.0/lib/net/ssh/prompt.rb:44:in `ask'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/password.rb:68:in `ask_password'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/password.rb:21:in `authenticate'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/net-ssh-4.1.0/lib/net/ssh.rb:237:in `start'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/idb-2.9.3/lib/lib/ssh_port_forwarder.rb:15:in `initialize'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/idb-2.9.3/lib/helper/ssh_port_forwarder.rb:36:in `new'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/idb-2.9.3/lib/helper/ssh_port_forwarder.rb:36:in `run'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/idb-2.9.3/lib/helper/ssh_port_forwarder.rb:63:in `<module:Idb>'
	from /Users/roman/.rvm/gems/ruby-2.4.1/gems/idb-2.9.3/lib/helper/ssh_port_forwarder.rb:7:in `<main>'
recv failed: Resource temporarily unavailable

**Comment by wang4921** [comment]
I also get this.  The latest version and IOS 8.4 .

**Comment by rromanen** [comment]
@dmayer still waiting to hear back on this as I'd like to possibly use this tool on a future assessments
