### ISSUE TITLE
App crashed on getting applist

### ISSUE THREAD

**Issue by aTastyCookie** [dmayer/idb#94]
Error on getting applist. App crashed.

```[DEBUG] 2017-09-11 18:41:29 :: idb ::  Backtrace: /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/lib/app.rb:284:in `cache_file'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/lib/app.rb:311:in `parse_info_plist'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/lib/app.rb:21:in `initialize'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:74:in `new'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:74:in `block in refresh_app_list'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:73:in `each'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:73:in `refresh_app_list'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:31:in `initialize'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/global_app_details_group_box.rb:43:in `new'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `qt_metacall'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `method_missing'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `exec'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/idb.rb:278:in `run'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/bin/idb:4:in `<top (required)>'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/bin/idb:23:in `load'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/bin/idb:23:in `<main>'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'.
/Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/lib/app.rb:37:in `initialize': undefined method `bundle_identifier' for nil:NilClass (NoMethodError)
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:74:in `new'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:74:in `block in refresh_app_list'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:73:in `each'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:73:in `refresh_app_list'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/app_list_dialog.rb:31:in `initialize'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/global_app_details_group_box.rb:43:in `new'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `exec'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/idb.rb:278:in `run'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/bin/idb:4:in `<top (required)>'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/bin/idb:23:in `load'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/bin/idb:23:in `<main>'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'
recv failed: Resource temporarily unavailable
➜  ~ /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/net-ssh-4.2.0/lib/net/ssh/prompt.rb:44:in `noecho': Input/output error (Errno::EIO)
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/net-ssh-4.2.0/lib/net/ssh/prompt.rb:44:in `ask'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/password.rb:68:in `ask_password'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/password.rb:21:in `authenticate'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/net-ssh-4.2.0/lib/net/ssh.rb:241:in `start'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/lib/ssh_port_forwarder.rb:15:in `initialize'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/helper/ssh_port_forwarder.rb:36:in `new'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/helper/ssh_port_forwarder.rb:36:in `run'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/helper/ssh_port_forwarder.rb:63:in `<module:Idb>'
	from /Users/d34dr00t/.rvm/gems/ruby-2.2.6/gems/idb-2.10.0/lib/helper/ssh_port_forwarder.rb:7:in `<main>'

➜  ~```

P.S. Darwin zion 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by MuchiMuchiPink** [comment]
I have the same issue. But my guess is issue #91 is still not fixed and be related.

**Comment by dmayer** [comment]
Which iOS version is this on?

**Comment by aTastyCookie** [comment]
Sierra 10.12.6 (16G29)

**Comment by dmayer** [comment]
sorry I mean the version on the iPhon/iPad not on the Mac. Is it iOS 10 or iOS 9?

**Comment by aTastyCookie** [comment]
9.0.2 (13A452) Jailbreaked :)
